#!/bin/bash

echo "🔧 Updating Render Environment Variables"
echo "========================================"
echo ""
echo "Your local Gmail Client ID: 242818294886-jujpis5fu57kmn8djcng0um75v0ivm76.apps.googleusercontent.com"
echo ""
echo "📋 To fix the OAuth issue, update your Render environment variables:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Select your 'homeops-agent' service"
echo "3. Go to 'Environment' tab"
echo "4. Update these variables:"
echo ""
echo "   GMAIL_CLIENT_ID: 242818294886-jujpis5fu57kmn8djcng0um75v0ivm76.apps.googleusercontent.com"
echo "   GMAIL_REDIRECT_URI: https://homeops-agent.onrender.com/auth/google/callback"
echo ""
echo "5. Click 'Save Changes'"
echo "6. Your service will automatically redeploy"
echo ""
echo "✅ This will fix the OAuth client ID mismatch between local and Render environments."
echo ""
echo "🔍 After updating, test the Gmail connection on your Render deployment." 